<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- GoiMon.Shared removed -->
  <ItemGroup>
    <PackageReference Include="Bit.Bswup" Version="10.4.2" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.*" />
    <PackageReference Include="EasyAppDev.Blazor.Store" Version="2.0.11" />
    <PackageReference Include="StrawberryShake.Blazor" Version="15.*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.*" />
    <PackageReference Include="BlazorBlueprint.Components" Version="*" />
    <PackageReference Include="BlazorBlueprint.Icons.Lucide" Version="*" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Generated\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

</Project>
