query GetCombos($skip: Int, $take: Int, $where: ProductComboFilterInput, $order: [ProductComboSortInput!]) {
  combos(skip: $skip, take: $take, where: $where, order: $order) {
    items {
      id
      name
      price
      imageUrl
      items {
        id
        qty
        productId
        variantId
        product {
          id
          name
          price
        }
        variant {
          id
          name
          price
          isActive
        }
      }
    }
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
  }
}
