name: Deploy GoiMon Portal

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch: {}

jobs:
  deploy-dev:
    if: ${{ github.ref == 'refs/heads/dev' }}
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            goimon_portal:
              - 'src/GoiMon.Portal/**'
              - 'docker-compose.yml'

      - name: Deploy source to server
        if: ${{ steps.filter.outputs.goimon_portal == 'true' }}
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          source: "src/GoiMon.Portal/,docker-compose.yml,.dockerignore"
          target: "/var/www/goimon"

      - name: Docker Compose up (dev)
        if: ${{ steps.filter.outputs.goimon_portal == 'true' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          script: |
            cd /var/www/goimon
            docker compose up -d --build portal

  deploy-prod:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            goimon_portal:
              - 'src/GoiMon.Portal/**'
              - 'docker-compose.yml'

      - name: Deploy source to server
        if: ${{ steps.filter.outputs.goimon_portal == 'true' }}
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "src/GoiMon.Portal/,docker-compose.yml,.dockerignore"
          target: "/var/www/goimon"

      - name: Docker Compose up (prod)
        if: ${{ steps.filter.outputs.goimon_portal == 'true' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/goimon
            docker compose up -d --build portal
